# Generated by Django 6.0.7 on 2026-07-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClipProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.TextField()),
                ("slug", models.SlugField()),
                (
                    "base_file",
                    models.FileField(max_length=200, upload_to="uploads/%Y/%m/%d/"),
                ),
                ("upload_datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClipVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_decision", models.BooleanField(default=None, null=True)),
                ("amount_of_times_loaded", models.IntegerField(default=0)),
                ("last_datetime_loaded", models.DateTimeField(default=None, null=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("decided_datetime", models.DateTimeField(default=None, null=True)),
                (
                    "parent_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="app.clipproject",
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="app.clipversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clipproject",
            name="current_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+none+",
                to="app.clipversion",
            ),
        ),
    ]
