# Generated by Django 6.0.7 on 2026-07-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clipversion",
            old_name="user_decision",
            new_name="bug_present",
        ),
        migrations.AddField(
            model_name="clipversion",
            name="segment_list",
            field=models.JSONField(default=list),
        ),
    ]
