# Generated by Django 6.0.7 on 2026-07-11 18:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_user_decision_clipversion_bug_present_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clipversion",
            name="segment_list",
        ),
        migrations.AddField(
            model_name="clipversion",
            name="span_list_converted_to_str",
            field=models.TextField(default=app.models.impossible),
        ),
    ]
